//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.16 at 07:24:31 PM CEST 
//


package gyurix.librarysystem.services.comment;

import gyurix.librarysystem.models.Comment;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gyurix.librarysystem.services.comment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetById_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "getById");
    private final static QName _Komentar_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "Komentar");
    private final static QName _GetByIdResponse_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "getByIdResponse");
    private final static QName _GetByAttributeValue_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "getByAttributeValue");
    private final static QName _Komentars_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "Komentars");
    private final static QName _GetByAttributeValueResponse_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "getByAttributeValueResponse");
    private final static QName _GetByNumericCondition_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "getByNumericCondition");
    private final static QName _GetByNumericConditionResponse_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "getByNumericConditionResponse");
    private final static QName _GetAll_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "getAll");
    private final static QName _GetAllResponse_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "getAllResponse");
    private final static QName _Insert_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "insert");
    private final static QName _InsertResponse_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "insertResponse");
    private final static QName _Update_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "update");
    private final static QName _UpdateResponse_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "updateResponse");
    private final static QName _Delete_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "delete");
    private final static QName _DeleteResponse_QNAME = new QName("http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", "deleteResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gyurix.librarysystem.services.comment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CommentGetById }
     * 
     */
    public CommentGetById createGetById() {
        return new CommentGetById();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createKomentar() {
        return new Comment();
    }

    /**
     * Create an instance of {@link CommentGetByIdResponse }
     * 
     */
    public CommentGetByIdResponse createGetByIdResponse() {
        return new CommentGetByIdResponse();
    }

    /**
     * Create an instance of {@link CommentGetByAttributeValue }
     * 
     */
    public CommentGetByAttributeValue createGetByAttributeValue() {
        return new CommentGetByAttributeValue();
    }

    /**
     * Create an instance of {@link CommentListElement }
     * 
     */
    public CommentListElement createKomentars() {
        return new CommentListElement();
    }

    /**
     * Create an instance of {@link CommentGetByAttributeValueResponse }
     * 
     */
    public CommentGetByAttributeValueResponse createGetByAttributeValueResponse() {
        return new CommentGetByAttributeValueResponse();
    }

    /**
     * Create an instance of {@link CommentGetByNumericCondition }
     * 
     */
    public CommentGetByNumericCondition createGetByNumericCondition() {
        return new CommentGetByNumericCondition();
    }

    /**
     * Create an instance of {@link CommentGetByNumericConditionResponse }
     * 
     */
    public CommentGetByNumericConditionResponse createGetByNumericConditionResponse() {
        return new CommentGetByNumericConditionResponse();
    }

    /**
     * Create an instance of {@link CommentGetAll }
     * 
     */
    public CommentGetAll createGetAll() {
        return new CommentGetAll();
    }

    /**
     * Create an instance of {@link CommentGetAllResponse }
     * 
     */
    public CommentGetAllResponse createGetAllResponse() {
        return new CommentGetAllResponse();
    }

    /**
     * Create an instance of {@link CommentInsert }
     * 
     */
    public CommentInsert createInsert() {
        return new CommentInsert();
    }

    /**
     * Create an instance of {@link CommentInsertResponse }
     * 
     */
    public CommentInsertResponse createInsertResponse() {
        return new CommentInsertResponse();
    }

    /**
     * Create an instance of {@link Update }
     * 
     */
    public Update createUpdate() {
        return new Update();
    }

    /**
     * Create an instance of {@link UpdateResponse }
     * 
     */
    public UpdateResponse createUpdateResponse() {
        return new UpdateResponse();
    }

    /**
     * Create an instance of {@link CommentDelete }
     * 
     */
    public CommentDelete createDelete() {
        return new CommentDelete();
    }

    /**
     * Create an instance of {@link CommentDeleteResponse }
     * 
     */
    public CommentDeleteResponse createDeleteResponse() {
        return new CommentDeleteResponse();
    }

    /**
     * Create an instance of {@link ArrayOfIds }
     * 
     */
    public ArrayOfIds createArrayOfIds() {
        return new ArrayOfIds();
    }

    /**
     * Create an instance of {@link ArrayOfKomentars }
     * 
     */
    public ArrayOfKomentars createArrayOfKomentars() {
        return new ArrayOfKomentars();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentGetById }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "getById")
    public JAXBElement<CommentGetById> createGetById(CommentGetById value) {
        return new JAXBElement<CommentGetById>(_GetById_QNAME, CommentGetById.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Comment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "Komentar")
    public JAXBElement<Comment> createKomentar(Comment value) {
        return new JAXBElement<Comment>(_Komentar_QNAME, Comment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentGetByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "getByIdResponse")
    public JAXBElement<CommentGetByIdResponse> createGetByIdResponse(CommentGetByIdResponse value) {
        return new JAXBElement<CommentGetByIdResponse>(_GetByIdResponse_QNAME, CommentGetByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentGetByAttributeValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "getByAttributeValue")
    public JAXBElement<CommentGetByAttributeValue> createGetByAttributeValue(CommentGetByAttributeValue value) {
        return new JAXBElement<CommentGetByAttributeValue>(_GetByAttributeValue_QNAME, CommentGetByAttributeValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentListElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "Komentars")
    public JAXBElement<CommentListElement> createKomentars(CommentListElement value) {
        return new JAXBElement<CommentListElement>(_Komentars_QNAME, CommentListElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentGetByAttributeValueResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "getByAttributeValueResponse")
    public JAXBElement<CommentGetByAttributeValueResponse> createGetByAttributeValueResponse(CommentGetByAttributeValueResponse value) {
        return new JAXBElement<CommentGetByAttributeValueResponse>(_GetByAttributeValueResponse_QNAME, CommentGetByAttributeValueResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentGetByNumericCondition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "getByNumericCondition")
    public JAXBElement<CommentGetByNumericCondition> createGetByNumericCondition(CommentGetByNumericCondition value) {
        return new JAXBElement<CommentGetByNumericCondition>(_GetByNumericCondition_QNAME, CommentGetByNumericCondition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentGetByNumericConditionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "getByNumericConditionResponse")
    public JAXBElement<CommentGetByNumericConditionResponse> createGetByNumericConditionResponse(CommentGetByNumericConditionResponse value) {
        return new JAXBElement<CommentGetByNumericConditionResponse>(_GetByNumericConditionResponse_QNAME, CommentGetByNumericConditionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentGetAll }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "getAll")
    public JAXBElement<CommentGetAll> createGetAll(CommentGetAll value) {
        return new JAXBElement<CommentGetAll>(_GetAll_QNAME, CommentGetAll.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentGetAllResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "getAllResponse")
    public JAXBElement<CommentGetAllResponse> createGetAllResponse(CommentGetAllResponse value) {
        return new JAXBElement<CommentGetAllResponse>(_GetAllResponse_QNAME, CommentGetAllResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentInsert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "insert")
    public JAXBElement<CommentInsert> createInsert(CommentInsert value) {
        return new JAXBElement<CommentInsert>(_Insert_QNAME, CommentInsert.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentInsertResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "insertResponse")
    public JAXBElement<CommentInsertResponse> createInsertResponse(CommentInsertResponse value) {
        return new JAXBElement<CommentInsertResponse>(_InsertResponse_QNAME, CommentInsertResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Update }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "update")
    public JAXBElement<Update> createUpdate(Update value) {
        return new JAXBElement<Update>(_Update_QNAME, Update.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "updateResponse")
    public JAXBElement<UpdateResponse> createUpdateResponse(UpdateResponse value) {
        return new JAXBElement<UpdateResponse>(_UpdateResponse_QNAME, UpdateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentDelete }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "delete")
    public JAXBElement<CommentDelete> createDelete(CommentDelete value) {
        return new JAXBElement<CommentDelete>(_Delete_QNAME, CommentDelete.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentDeleteResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types", name = "deleteResponse")
    public JAXBElement<CommentDeleteResponse> createDeleteResponse(CommentDeleteResponse value) {
        return new JAXBElement<CommentDeleteResponse>(_DeleteResponse_QNAME, CommentDeleteResponse.class, null, value);
    }

}
