//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.16 at 07:24:31 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pis.predmety.fiit.stuba.sk/pis/students/team115komentar/types")
package gyurix.librarysystem.services.comment;
