//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 04:51:03 PM CEST 
//


package gyurix.librarysystem.services.book;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Book complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Book"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isbn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="genre" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Book", propOrder = {
  "id",
  "name",
  "author",
  "isbn",
  "genre",
  "publisher"
})
public class Book {

  @XmlElement(required = true)
  protected String author;
  @XmlElement(required = true)
  protected String genre;
  protected int id;
  @XmlElement(required = true)
  protected String isbn;
  @XmlElement(required = true)
  protected String name;
  @XmlElement(required = true)
  protected String publisher;

  /**
   * Gets the value of the author property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getAuthor() {
    return author;
  }

  /**
   * Sets the value of the author property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAuthor(String value) {
    this.author = value;
  }

  /**
   * Gets the value of the genre property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getGenre() {
    return genre;
  }

  /**
   * Sets the value of the genre property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setGenre(String value) {
    this.genre = value;
  }

  /**
   * Gets the value of the id property.
   */
  public int getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the isbn property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getIsbn() {
    return isbn;
  }

  /**
   * Sets the value of the isbn property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setIsbn(String value) {
    this.isbn = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the publisher property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getPublisher() {
    return publisher;
  }

  /**
   * Sets the value of the publisher property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setPublisher(String value) {
    this.publisher = value;
  }

}
