//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 04:51:03 PM CEST 
//


package gyurix.librarysystem.services.book;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getByNumericConditionResponse complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="getByNumericConditionResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="books" type="{http://pis.predmety.fiit.stuba.sk/pis/students/team115book/types}ArrayOfBooks"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getByNumericConditionResponse", propOrder = {
  "books"
})
public class GetByNumericConditionResponse {

  @XmlElement(required = true)
  protected ArrayOfBooks books;

  /**
   * Gets the value of the books property.
   *
   * @return possible object is
   * {@link ArrayOfBooks }
   */
  public ArrayOfBooks getBooks() {
    return books;
  }

  /**
   * Sets the value of the books property.
   *
   * @param value allowed object is
   *              {@link ArrayOfBooks }
   */
  public void setBooks(ArrayOfBooks value) {
    this.books = value;
  }

}
