//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.17 at 11:25:50 AM CEST 
//


package gyurix.librarysystem.services.explicit_terms;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ArrayOfExplicittermss complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArrayOfExplicittermss"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="explicitterm" type="{http://pis.predmety.fiit.stuba.sk/pis/students/team115explicitterms/types}Explicittermss" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArrayOfExplicittermss", propOrder = {
    "explicitterm"
})
public class ArrayOfExplicittermss {

    @XmlElement(nillable = true)
    protected List<Explicittermss> explicitterm;

    /**
     * Gets the value of the explicitterm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the explicitterm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExplicitterm().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Explicittermss }
     * 
     * 
     */
    public List<Explicittermss> getExplicitterm() {
        if (explicitterm == null) {
            explicitterm = new ArrayList<Explicittermss>();
        }
        return this.explicitterm;
    }

}
