//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.17 at 11:25:50 AM CEST 
//


package gyurix.librarysystem.services.explicit_terms;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getByAttributeValueResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getByAttributeValueResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="explicittermss" type="{http://pis.predmety.fiit.stuba.sk/pis/students/team115explicitterms/types}ArrayOfExplicittermss"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getByAttributeValueResponse", propOrder = {
    "explicittermss"
})
public class GetByAttributeValueResponse {

    @XmlElement(required = true)
    protected ArrayOfExplicittermss explicittermss;

    /**
     * Gets the value of the explicittermss property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfExplicittermss }
     *     
     */
    public ArrayOfExplicittermss getExplicittermss() {
        return explicittermss;
    }

    /**
     * Sets the value of the explicittermss property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfExplicittermss }
     *     
     */
    public void setExplicittermss(ArrayOfExplicittermss value) {
        this.explicittermss = value;
    }

}
